-- MySQL Script generated by MySQL Workbench
-- Mon Dec 3 23:22:24 2018
-- Model: New Model Version: 1.0
-- MySQL Workbench Forward Engineering
-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;
-- -----------------------------------------------------
-- Table `mydb`.`Dependente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Dependente` (
    `CPF` INT NOT NULL,
    `Nome` VARCHAR(30) NULL,
    `Sexo` VARCHAR(30) NULL,
    `Data_Nascimento` DATE NULL,
    `Funcionário` VARCHAR(30) NULL,
    PRIMARY KEY (`CPF`)
);
-- -----------------------------------------------------
-- Table `mydb`.`Funcionário`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Funcionário` (
    `Matrícula` INT NOT NULL,
    `Nome` VARCHAR(45) NULL,
    `CPF` INT NOT NULL,
    `Endereço` VARCHAR(45) NOT NULL,
    `Telefone` VARCHAR(45) NOT NULL,
    `Dependente_CPF` INT NULL,
    PRIMARY KEY (`Matrícula` , `Dependente_CPF`),
    UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC),
    INDEX `fk_Funcionário_Dependente1_idx` (`Dependente_CPF` ASC),
    CONSTRAINT `fk_Funcionário_Dependente1` FOREIGN KEY (`Dependente_CPF`)
        REFERENCES `mydb`.`Dependente` (`CPF`)
        ON DELETE NO ACTION ON UPDATE NO ACTION
)  ENGINE=INNODB;
-- -----------------------------------------------------
-- Table `mydb`.`Cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cargo` (
    `idCargo` INT NOT NULL,
    `Funcionário_Matrícula` INT NULL,
    `Funcionário_Dependente_CPF` INT NULL,
    PRIMARY KEY (`idCargo` , `Funcionário_Matrícula` , `Funcionário_Dependente_CPF`),
    INDEX `fk_Cargo_Funcionário1_idx` (`Funcionário_Matrícula` ASC , `Funcionário_Dependente_CPF` ASC),
    CONSTRAINT `fk_Cargo_Funcionário1` FOREIGN KEY (`Funcionário_Matrícula` , `Funcionário_Dependente_CPF`)
        REFERENCES `mydb`.`Funcionário` (`Matrícula` , `Dependente_CPF`)
        ON DELETE NO ACTION ON UPDATE NO ACTION
)  ENGINE=INNODB;
-- -----------------------------------------------------
-- Table `mydb`.`Professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Professor` (
`ID_Professor` INT NOT NULL,
`Funcionário_Matrícula` INT NOT NULL,
`Funcionário_Dependente_CPF` INT NOT NULL,
PRIMARY KEY (`ID_Professor`, `Funcionário_Matrícula`,
`Funcionário_Dependente_CPF`),
INDEX `fk_Professor_Funcionário1_idx` (`Funcionário_Matrícula` ASC,
`Funcionário_Dependente_CPF` ASC),
CONSTRAINT `fk_Professor_Funcionário1`
FORE
`Funcionário_Matrícula` INT NOT NULL,
`Funcionário_Dependente_CPF` INT NOT NULL,
PRIMARY KEY (`ID_Tecnico`, `Funcionário_Matrícula`, `Funcionário_Dependente_CPF`),
INDEX `fk_Técnico_Funcionário1_idx` (`Funcionário_Matrícula` ASC,
`Funcionário_Dependente_CPF` ASC),
CONSTRAINT `fk_Técnico_Funcionário1`
FOREIGN KEY (`Funcionário_Matrícula` , `Funcionário_Dependente_CPF`)
REFERENCES `mydb`.`Funcionário` (`Matrícula` , `Dependente_CPF`)
ON DELETE NO ACTION
ON UPDATE NO ACTION);
-- -----------------------------------------------------
-- Table `mydb`.`Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Aluno` (
    `Matrícula_A` INT NOT NULL,
    `CPF` VARCHAR(45) NOT NULL,
    `RG` INT NOT NULL,
    `Nome` VARCHAR(30) NOT NULL,
    `Filiação` VARCHAR(50) NULL,
    `Data_Nascimento` DATE NULL,
    `Sexo` VARCHAR(30) NULL,
    `Endereço` VARCHAR(30) NULL,
    `Telefone` INT NULL,
    `Titulo_Eleitor` INT NULL,
    PRIMARY KEY (`Matrícula_A`)
);
-- -----------------------------------------------------
-- Table `mydb`.`Instituto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Instituto` (
    `idInstituto` INT NOT NULL,
    `TipoInstituto` VARCHAR(30) NULL,
    PRIMARY KEY (`idInstituto`)
)  ENGINE=INNODB;
-- -----------------------------------------------------
-- Table `mydb`.`Periodo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Periodo` (
    `Ano` INT NOT NULL,
    `Tipo_Periodo` INT NULL,
    PRIMARY KEY (`Ano`)
);
-- -----------------------------------------------------
-- Table `mydb`.`Disciplinas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Disciplinas` (
    `Código` VARCHAR(20) NOT NULL,
    `Nome` VARCHAR(30) NULL,
    `Créditos` INT NULL,
    `CargaHoraria_Teorica` INT NULL,
    `CargaHoraria_Prática` INT NULL,
    `Status_da_Disciplina` VARCHAR(45) NULL,
    `Periodo_Ano` INT NOT NULL,
    PRIMARY KEY (`Código` , `Periodo_Ano`),
    INDEX `fk_Disciplinas_Periodo1_idx` (`Periodo_Ano` ASC),
    CONSTRAINT `fk_Disciplinas_Periodo1` FOREIGN KEY (`Periodo_Ano`)
        REFERENCES `mydb`.`Periodo` (`Ano`)
        ON DELETE NO ACTION ON UPDATE NO ACTION
);
-- -----------------------------------------------------
-- Table `mydb`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Curso` (
`ID_Curso` NOT NULL,
`Aluno_Matrícula_A` INT NULL,
`Instituto_idInstituto` INT NOT NULL,
`Disciplinas_Código` VARCHAR(20) NOT NULL,
`Disciplinas_Periodo_Ano` INT NOT NULL,
PRIMARY KEY (`ID_Curso`, `Aluno_Matrícula_A`, `Instituto_idInstituto`,
`Disciplinas_Código`, `Disciplinas_Periodo_Ano`),

FOREIGN KEY (`Aluno_Matrícula_A`)
REFERENCES `mydb`.`Aluno` (`Matrícula_A`)
ON DELETE NO ACTION
ON UPDATE NO ACTION,

FOREIGN KEY (`Instituto_idInstituto`)
REFERENCES `mydb`.`Instituto` (`idInstituto`)
ON DELETE NO ACTION
ON UPDATE NO ACTION,

FOREIGN KEY (`Disciplinas_Código` , `Disciplinas_Periodo_Ano`)
REFERENCES `mydb`.`Disciplinas` (`Código` , `Periodo_Ano`)
ON DELETE NO ACTION
ON UPDATE NO ACTION);
-- -----------------------------------------------------
-- Table `mydb`.`Turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Turma` (
    `Local` VARCHAR(30) NOT NULL,
    `Dia` DATE NULL,
    `Horário` INT NULL,
    PRIMARY KEY (`Local`)
);
-- -----------------------------------------------------
-- Table `mydb`.`Matriculado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Matriculado` (
    `Aluno_Matrícula_A` INT NOT NULL,
    `Disciplinas_Código` VARCHAR(20) NOT NULL,
    PRIMARY KEY (`Aluno_Matrícula_A` , `Disciplinas_Código`),
	
    FOREIGN KEY (`Aluno_Matrícula_A`)
        REFERENCES `mydb`.`Aluno` (`Matrícula_A`)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION,
    
    FOREIGN KEY (`Disciplinas_Código`)
        REFERENCES `mydb`.`Disciplinas` (`Código`)
        ON DELETE NO ACTION 
        ON UPDATE NO ACTION
);
-- -----------------------------------------------------
-- Table `mydb`.`Conclui`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Conclui` (
    `Disciplinas_Código` VARCHAR(20) NULL,
    `Aluno_Matrícula_A` INT NULL,
    `Nota_Final` INT NULL,
    `Numero_faltas` INT NULL,
    `Situacao_Academica` VARCHAR(45) NULL,
    PRIMARY KEY (`Disciplinas_Código` , `Aluno_Matrícula_A`),
	FOREIGN KEY (`Disciplinas_Código`)
        REFERENCES `mydb`.`Disciplinas` (`Código`)
        ON DELETE NO ACTION 
        ON UPDATE NO ACTION,
        
	FOREIGN KEY (`Aluno_Matrícula_A`)
        REFERENCES `mydb`.`Aluno` (`Matrícula_A`)
        ON DELETE NO ACTION 
        ON UPDATE NO ACTION
);
-- -----------------------------------------------------
-- Table `mydb`.`pré-requisito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pré-requisito` (
    `Disciplinas_Código` VARCHAR(20) NULL,
    `Disciplinas_Código1` VARCHAR(20) NULL,
    `Disciplina_Pre` VARCHAR(45) NULL,
    PRIMARY KEY (`Disciplinas_Código` , `Disciplinas_Código1`),
   FOREIGN KEY (`Disciplinas_Código`)
        REFERENCES `mydb`.`Disciplinas` (`Código`)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION,
    CONSTRAINT `fk_Disciplinas_has_Disciplinas_Disciplinas2` FOREIGN KEY (`Disciplinas_Código1`)
        REFERENCES `mydb`.`Disciplinas` (`Código`)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION
);
-- -----------------------------------------------------
-- Table `mydb`.`Disciplinas_has_Turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Disciplinas_has_Turma` (
    `Disciplinas_Código` VARCHAR(20) NOT NULL,
    `Disciplinas_Periodo_Ano` INT NOT NULL,
    `Turma_Local` VARCHAR(30) NOT NULL,
    `Professor_ID_Professor` INT NOT NULL,
    `Professor_Funcionário_Matrícula` INT NOT NULL,
    `Professor_Funcionário_Dependente_CPF` INT NOT NULL,
    PRIMARY KEY (`Disciplinas_Código` , `Disciplinas_Periodo_Ano` , `Turma_Local` , `Professor_ID_Professor` , `Professor_Funcionário_Matrícula` , `Professor_Funcionário_Dependente_CPF`),
    FOREIGN KEY (`Disciplinas_Código` , `Disciplinas_Periodo_Ano`)
        REFERENCES `mydb`.`Disciplinas` (`Código` , `Periodo_Ano`)
        ON DELETE NO ACTION ON UPDATE NO ACTION,
    FOREIGN KEY (`Turma_Local`)
        REFERENCES `mydb`.`Turma` (`Local`)
        ON DELETE NO ACTION ON UPDATE NO ACTION,
    FOREIGN KEY (`Professor_ID_Professor` , `Professor_Funcionário_Matrícula` , `Professor_Funcionário_Dependente_CPF`)
        REFERENCES `mydb`.`Professor` (`ID_Professor` , `Funcionário_Matrícula` , `Funcionário_Dependente_CPF`)
        ON DELETE NO ACTION ON UPDATE NO ACTION
);